/*
 *  * This is sample code generated by rpcgen.
 *   * These are only templates and you can use them
 *    * as a guideline for developing your own functions.
 *     */

#include "remoteBash.h"

bash_result *remotebash_1(char *host, char *command) {
    CLIENT *clnt;

    bash_result *result_1;

#ifndef    DEBUG
    clnt = clnt_create(host, RemoteBash, VERSIO, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif    /* DEBUG */

    result_1 = rpcbash_1(&command, clnt);
    if (result_1 == (bash_result *) NULL) {
        clnt_perror(clnt, "call failed");
    }
#ifndef    DEBUG
    clnt_destroy(clnt);
#endif     /* DEBUG */

    return result_1; //return result of command
}

char * getline2(void) {
    char * line = malloc(100), * linep = line;
    size_t lenmax = 100, len = lenmax;
    int c;

    if(line == NULL)
        return NULL;

    for(;;) {
        c = fgetc(stdin);
        if(c == EOF)
            break;

        if(--len == 0) {
            len = lenmax;
            char * linen = realloc(linep, lenmax *= 2);

            if(linen == NULL) {
                free(linep);
                return NULL;
            }
            line = linen + (line - linep);
            linep = linen;
        }

        if((*line++ = c) == '\n')
            break;
    }
    *line = '\0';
    return linep;
}

int main(int argc, char *argv[]) {
    char *host;

    bash_result *result;

    char *command;

    if (argc < 2) {
        printf("usage: %s server_host [\"command to execute\"]\n", argv[0]);
        exit(1);
    }

    host = argv[1]; //take host first argument

    if (argc < 3) { //we have 3 args file host command
        while(1) {
            command = getline2();
            result = remotebash_1(host, command); //call
            free(command); //deallocate memory
            printf("Status code: %d\n%s\n", result->status, result->stdOut);
        }
    } else {
        command = strdup(argv[2]); //take bash command second argument
        //printf("c:%s\n", command);
        result = remotebash_1(host, command); //call
        free(command); //deallocate memory
        printf("Status code: %d\n%s\n", result->status, result->stdOut);
    }

    exit(0);
}
